# Generated by Django 5.2.8 on 2025-11-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmaxmarks',
            name='id',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studentmaxmarks',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.course'),
        ),
        migrations.CreateModel(
            name='SessionKey',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('required_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('required_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_tolerance_m', models.IntegerField(default=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
